#theme: jekyll-theme-minimal
title: "xxxx"
author: "xxxx"

#description: "Made with <b style=\"color: #f45;\">&lt;3</b> by <b><a href=\"https://github.com/niklasbuschmann\">@niklasbuschmann</a></b>"
permalink: /:title/
#lang: "en"
date_format: "%B %d, %Y"

# Layout

sidebar: false               # show a sidebar instead of the usual header
show_excerpts: false         # show article excerpts on the home page
show_related: true           # show the previous and next links after every post
show_description: true       # show the site description in the sidebar
show_title: true             # always keep the site title visible

# Styling

dark_header: false           # always keep the header dark
minimal: false               # use simpler style

# Menu

navigation:
  - {file: "index.html", icon: home}
  #- {file: "postlist.md", icon: home}
  - {file: "about.md",  icon: address-card}
  - {file: "cv.md",  icon: cv}

external:                    # see http://fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:yihsuan.lin0520@gmail.com"}
  - {title: Linkedin, icon: linkedin, url: "https://linkedin.com/in/yihsuanlinphysics"}
  - {title: Google_Scholar, icon: google-scholar, url: "https://scholar.google.com/citations?user=Ob9KposAAAAJ&hl=en"}
  - {title: Github, icon: github, url: "https://github.com/caseypie"}
  #- {title: Subscribe, icon: rss, url: "/feed.xml"}

